name: pokedex
description: A new Flutter project.
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  cached_network_image: ^2.1.0+1
  json_serializable: ^3.3.0
  google_fonts: ^0.6.2
  font_awesome_flutter: ^8.8.1
  simple_animations: ^1.3.12
  flutter_svg: ^0.17.4
  dio: ^3.0.9
  flutter_mobx: ^1.1.0
  mobx: ^1.1.1
  flutter_modular: ^1.1.2
  flutter:
    sdk: flutter


dev_dependencies:
  mockito: ^4.1.1
  mobx_codegen: ^1.0.3
  build_runner: ^1.8.1
  flutter_test:
    sdk: flutter


flutter:

  uses-material-design: true

  assets:
   - assets/images/

scripts:
  build: flutter pub run build_runner build --delete-conflicting-outputs
  clean: flutter pub run build_runner clean